/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cad10)
#  Generated on:      Wed Feb 18 18:53:07 2026
#  Design:            reg_adder
#  Command:           saveNetlist post_cts.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 18 2026 17:09:43 IST (Feb 18 2026 11:39:43 UTC)
// Verification Directory fv/reg_adder 
module reg_adder (
	clk, 
	rst, 
	a, 
	b, 
	sum_q);
   input clk;
   input rst;
   input [7:0] a;
   input [7:0] b;
   output [8:0] sum_q;

   // Internal wires
   wire [7:0] a_reg;
   wire [7:0] b_reg;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;

   DFFTRXL \sum_q_reg[8]  (.CK(clk),
	.D(n_18),
	.Q(sum_q[8]),
	.QN(UNCONNECTED),
	.RN(n_16));
   DFFTRXL \sum_q_reg[7]  (.CK(clk),
	.D(n_18),
	.Q(sum_q[7]),
	.QN(UNCONNECTED0),
	.RN(n_17));
   ADDFX1 g723__2398 (.A(a_reg[7]),
	.B(b_reg[7]),
	.CI(n_14),
	.CO(n_16),
	.S(n_17));
   DFFTRXL \sum_q_reg[6]  (.CK(clk),
	.D(n_18),
	.Q(sum_q[6]),
	.QN(UNCONNECTED1),
	.RN(n_15));
   ADDFX1 g725__5107 (.A(a_reg[6]),
	.B(b_reg[6]),
	.CI(n_12),
	.CO(n_14),
	.S(n_15));
   DFFTRXL \sum_q_reg[5]  (.CK(clk),
	.D(n_18),
	.Q(sum_q[5]),
	.QN(UNCONNECTED2),
	.RN(n_13));
   ADDFX1 g727__6260 (.A(a_reg[5]),
	.B(b_reg[5]),
	.CI(n_10),
	.CO(n_12),
	.S(n_13));
   DFFTRXL \sum_q_reg[4]  (.CK(clk),
	.D(n_18),
	.Q(sum_q[4]),
	.QN(UNCONNECTED3),
	.RN(n_11));
   ADDFX1 g729__4319 (.A(a_reg[4]),
	.B(b_reg[4]),
	.CI(n_8),
	.CO(n_10),
	.S(n_11));
   DFFTRXL \sum_q_reg[3]  (.CK(clk),
	.D(n_18),
	.Q(sum_q[3]),
	.QN(UNCONNECTED4),
	.RN(n_9));
   ADDFX1 g731__8428 (.A(a_reg[3]),
	.B(b_reg[3]),
	.CI(n_6),
	.CO(n_8),
	.S(n_9));
   DFFTRXL \sum_q_reg[2]  (.CK(clk),
	.D(n_18),
	.Q(sum_q[2]),
	.QN(UNCONNECTED5),
	.RN(n_7));
   ADDFX1 g733__5526 (.A(a_reg[2]),
	.B(b_reg[2]),
	.CI(n_4),
	.CO(n_6),
	.S(n_7));
   DFFTRXL \sum_q_reg[1]  (.CK(clk),
	.D(n_18),
	.Q(sum_q[1]),
	.QN(UNCONNECTED6),
	.RN(n_5));
   ADDFX1 g735__6783 (.A(a_reg[1]),
	.B(b_reg[1]),
	.CI(n_3),
	.CO(n_4),
	.S(n_5));
   DFFTRXL \sum_q_reg[0]  (.CK(clk),
	.D(n_18),
	.Q(sum_q[0]),
	.QN(UNCONNECTED7),
	.RN(n_2));
   NOR2X1 g738__3680 (.A(n_1),
	.B(n_0),
	.Y(n_3));
   AOI2BB2X1 g737__1617 (.A0N(a_reg[0]),
	.A1N(b_reg[0]),
	.B0(a_reg[0]),
	.B1(b_reg[0]),
	.Y(n_2));
   DFFTRXL \a_reg_reg[4]  (.CK(clk),
	.D(n_18),
	.Q(a_reg[4]),
	.QN(UNCONNECTED8),
	.RN(a[4]));
   DFFTRXL \b_reg_reg[6]  (.CK(clk),
	.D(n_18),
	.Q(b_reg[6]),
	.QN(UNCONNECTED9),
	.RN(b[6]));
   DFFTRXL \b_reg_reg[5]  (.CK(clk),
	.D(n_18),
	.Q(b_reg[5]),
	.QN(UNCONNECTED10),
	.RN(b[5]));
   DFFTRXL \a_reg_reg[3]  (.CK(clk),
	.D(n_18),
	.Q(a_reg[3]),
	.QN(UNCONNECTED11),
	.RN(a[3]));
   DFFTRXL \a_reg_reg[1]  (.CK(clk),
	.D(n_18),
	.Q(a_reg[1]),
	.QN(UNCONNECTED12),
	.RN(a[1]));
   DFFTRXL \a_reg_reg[2]  (.CK(clk),
	.D(n_18),
	.Q(a_reg[2]),
	.QN(UNCONNECTED13),
	.RN(a[2]));
   DFFTRXL \a_reg_reg[0]  (.CK(clk),
	.D(n_18),
	.Q(a_reg[0]),
	.QN(n_0),
	.RN(a[0]));
   DFFTRXL \b_reg_reg[0]  (.CK(clk),
	.D(n_18),
	.Q(b_reg[0]),
	.QN(n_1),
	.RN(b[0]));
   DFFTRXL \b_reg_reg[3]  (.CK(clk),
	.D(n_18),
	.Q(b_reg[3]),
	.QN(UNCONNECTED14),
	.RN(b[3]));
   DFFTRXL \a_reg_reg[5]  (.CK(clk),
	.D(n_18),
	.Q(a_reg[5]),
	.QN(UNCONNECTED15),
	.RN(a[5]));
   DFFTRXL \b_reg_reg[2]  (.CK(clk),
	.D(n_18),
	.Q(b_reg[2]),
	.QN(UNCONNECTED16),
	.RN(b[2]));
   DFFTRXL \a_reg_reg[6]  (.CK(clk),
	.D(n_18),
	.Q(a_reg[6]),
	.QN(UNCONNECTED17),
	.RN(a[6]));
   DFFTRXL \b_reg_reg[7]  (.CK(clk),
	.D(n_18),
	.Q(b_reg[7]),
	.QN(UNCONNECTED18),
	.RN(b[7]));
   DFFTRXL \a_reg_reg[7]  (.CK(clk),
	.D(n_18),
	.Q(a_reg[7]),
	.QN(UNCONNECTED19),
	.RN(a[7]));
   DFFTRXL \b_reg_reg[1]  (.CK(clk),
	.D(n_18),
	.Q(b_reg[1]),
	.QN(UNCONNECTED20),
	.RN(b[1]));
   DFFTRXL \b_reg_reg[4]  (.CK(clk),
	.D(n_18),
	.Q(b_reg[4]),
	.QN(UNCONNECTED21),
	.RN(b[4]));
   INVX1 g757 (.A(rst),
	.Y(n_18));
endmodule

