/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cad10)
#  Generated on:      Thu Feb 19 17:57:12 2026
#  Design:            reg_adder
#  Command:           saveNetlist post_route_term.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 19 2026 17:06:58 IST (Feb 19 2026 11:36:58 UTC)
// Verification Directory fv/reg_adder 
module reg_adder (
	clk, 
	rst, 
	a, 
	b, 
	sum_q);
   input clk;
   input rst;
   input [7:0] a;
   input [7:0] b;
   output [8:0] sum_q;

   // Internal wires
   wire FE_PHN3_n_43;
   wire FE_PHN2_n_49;
   wire FE_PHN1_n_52;
   wire FE_PHN0_n_18;
   wire [7:0] a_reg;
   wire [7:0] b_reg;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;

   CLKBUFX2 FE_PHC3_n_43 (.A(n_43),
	.Y(FE_PHN3_n_43));
   CLKBUFX2 FE_PHC2_n_49 (.A(n_49),
	.Y(FE_PHN2_n_49));
   CLKBUFX2 FE_PHC1_n_52 (.A(n_52),
	.Y(FE_PHN1_n_52));
   CLKBUFX2 FE_PHC0_n_18 (.A(n_18),
	.Y(FE_PHN0_n_18));
   DFFQXL \sum_q_reg[8]  (.CK(clk),
	.D(n_53),
	.Q(sum_q[8]));
   DFFQXL \sum_q_reg[7]  (.CK(clk),
	.D(n_54),
	.Q(sum_q[7]));
   NOR2BX1 g950__2398 (.AN(FE_PHN1_n_52),
	.B(rst),
	.Y(n_54));
   NOR2BX1 g951__5107 (.AN(n_51),
	.B(rst),
	.Y(n_53));
   ADDFXL g952__6260 (.A(a_reg[7]),
	.B(b_reg[7]),
	.CI(n_48),
	.CO(n_51),
	.S(n_52));
   DFFQXL \sum_q_reg[6]  (.CK(clk),
	.D(n_50),
	.Q(sum_q[6]));
   NOR2BX1 g954__4319 (.AN(FE_PHN2_n_49),
	.B(rst),
	.Y(n_50));
   ADDFX1 g955__8428 (.A(b_reg[6]),
	.B(a_reg[6]),
	.CI(n_45),
	.CO(n_48),
	.S(n_49));
   DFFQXL \sum_q_reg[5]  (.CK(clk),
	.D(n_47),
	.Q(sum_q[5]));
   NOR2BX1 g957__5526 (.AN(n_46),
	.B(rst),
	.Y(n_47));
   ADDFX1 g958__6783 (.A(b_reg[5]),
	.B(a_reg[5]),
	.CI(n_42),
	.CO(n_45),
	.S(n_46));
   DFFQXL \sum_q_reg[4]  (.CK(clk),
	.D(n_44),
	.Q(sum_q[4]));
   NOR2BX1 g960__3680 (.AN(FE_PHN3_n_43),
	.B(rst),
	.Y(n_44));
   ADDFX1 g961__1617 (.A(b_reg[4]),
	.B(a_reg[4]),
	.CI(n_39),
	.CO(n_42),
	.S(n_43));
   DFFQXL \sum_q_reg[3]  (.CK(clk),
	.D(n_41),
	.Q(sum_q[3]));
   NOR2XL g963__2802 (.A(n_40),
	.B(rst),
	.Y(n_41));
   DFFQXL \sum_q_reg[2]  (.CK(clk),
	.D(n_38),
	.Q(sum_q[2]));
   AOI21XL g965__1705 (.A0(n_36),
	.A1(n_35),
	.B0(n_37),
	.Y(n_40));
   OAI21X1 g966__5122 (.A0(n_17),
	.A1(n_34),
	.B0(n_16),
	.Y(n_39));
   DFFQXL \sum_q_reg[1]  (.CK(clk),
	.D(n_33),
	.Q(sum_q[1]));
   NOR2XL g967__8246 (.A(n_32),
	.B(rst),
	.Y(n_38));
   NOR2XL g968__7098 (.A(n_36),
	.B(n_35),
	.Y(n_37));
   CLKINVX1 g969 (.A(n_35),
	.Y(n_34));
   NOR2XL g973__6131 (.A(n_31),
	.B(rst),
	.Y(n_33));
   AOI21XL g971__1881 (.A0(n_29),
	.A1(n_28),
	.B0(n_30),
	.Y(n_32));
   OAI21X1 g972__5115 (.A0(n_20),
	.A1(n_27),
	.B0(n_19),
	.Y(n_35));
   DFFQXL \sum_q_reg[0]  (.CK(clk),
	.D(n_23),
	.Q(sum_q[0]));
   AOI21XL g977__7482 (.A0(n_25),
	.A1(n_24),
	.B0(n_26),
	.Y(n_31));
   NOR2XL g974__4733 (.A(n_29),
	.B(n_28),
	.Y(n_30));
   CLKINVX1 g975 (.A(n_28),
	.Y(n_27));
   NOR2XL g979__6161 (.A(n_25),
	.B(n_24),
	.Y(n_26));
   NOR2XL g980__9315 (.A(FE_PHN0_n_18),
	.B(rst),
	.Y(n_23));
   OAI21X1 g978__9945 (.A0(n_25),
	.A1(n_21),
	.B0(n_22),
	.Y(n_28));
   NOR2BXL g981__2883 (.AN(n_22),
	.B(n_21),
	.Y(n_24));
   NAND2BXL g982__2346 (.AN(n_20),
	.B(n_19),
	.Y(n_29));
   OAI21X1 g983__1666 (.A0(a_reg[0]),
	.A1(b_reg[0]),
	.B0(n_25),
	.Y(n_18));
   NAND2BXL g984__7410 (.AN(n_17),
	.B(n_16),
	.Y(n_36));
   NAND2XL g985__6417 (.A(a_reg[1]),
	.B(b_reg[1]),
	.Y(n_22));
   NOR2XL g987__5477 (.A(a_reg[2]),
	.B(b_reg[2]),
	.Y(n_20));
   NOR2XL g988__2398 (.A(a_reg[3]),
	.B(b_reg[3]),
	.Y(n_17));
   NOR2XL g986__5107 (.A(a_reg[1]),
	.B(b_reg[1]),
	.Y(n_21));
   NAND2XL g990__6260 (.A(a_reg[2]),
	.B(b_reg[2]),
	.Y(n_19));
   NAND2XL g989__4319 (.A(a_reg[3]),
	.B(b_reg[3]),
	.Y(n_16));
   NAND2XL g991__8428 (.A(a_reg[0]),
	.B(b_reg[0]),
	.Y(n_25));
   DFFQX1 \b_reg_reg[7]  (.CK(clk),
	.D(n_14),
	.Q(b_reg[7]));
   DFFQX1 \a_reg_reg[6]  (.CK(clk),
	.D(n_5),
	.Q(a_reg[6]));
   DFFQX1 \a_reg_reg[4]  (.CK(clk),
	.D(n_8),
	.Q(a_reg[4]));
   DFFQX1 \a_reg_reg[5]  (.CK(clk),
	.D(n_6),
	.Q(a_reg[5]));
   DFFQX1 \b_reg_reg[5]  (.CK(clk),
	.D(n_0),
	.Q(b_reg[5]));
   DFFQX1 \a_reg_reg[1]  (.CK(clk),
	.D(n_4),
	.Q(a_reg[1]));
   DFFQX1 \a_reg_reg[2]  (.CK(clk),
	.D(n_12),
	.Q(a_reg[2]));
   DFFQX1 \b_reg_reg[0]  (.CK(clk),
	.D(n_3),
	.Q(b_reg[0]));
   DFFQX1 \b_reg_reg[4]  (.CK(clk),
	.D(n_1),
	.Q(b_reg[4]));
   DFFQX1 \a_reg_reg[7]  (.CK(clk),
	.D(n_10),
	.Q(a_reg[7]));
   DFFQX1 \b_reg_reg[6]  (.CK(clk),
	.D(n_2),
	.Q(b_reg[6]));
   DFFQX1 \a_reg_reg[3]  (.CK(clk),
	.D(n_9),
	.Q(a_reg[3]));
   DFFQX1 \a_reg_reg[0]  (.CK(clk),
	.D(n_11),
	.Q(a_reg[0]));
   DFFQX1 \b_reg_reg[3]  (.CK(clk),
	.D(n_15),
	.Q(b_reg[3]));
   DFFQX1 \b_reg_reg[2]  (.CK(clk),
	.D(n_13),
	.Q(b_reg[2]));
   DFFQX1 \b_reg_reg[1]  (.CK(clk),
	.D(n_7),
	.Q(b_reg[1]));
   NOR2BX1 g1009__5526 (.AN(b[3]),
	.B(rst),
	.Y(n_15));
   NOR2BX1 g1018__6783 (.AN(b[7]),
	.B(rst),
	.Y(n_14));
   NOR2BX1 g1019__3680 (.AN(b[2]),
	.B(rst),
	.Y(n_13));
   NOR2BX1 g1008__1617 (.AN(a[2]),
	.B(rst),
	.Y(n_12));
   NOR2BX1 g1022__2802 (.AN(a[0]),
	.B(rst),
	.Y(n_11));
   NOR2BX1 g1010__1705 (.AN(a[7]),
	.B(rst),
	.Y(n_10));
   NOR2BX1 g1011__5122 (.AN(a[3]),
	.B(rst),
	.Y(n_9));
   NOR2BX1 g1020__8246 (.AN(a[4]),
	.B(rst),
	.Y(n_8));
   NOR2BX1 g1017__7098 (.AN(b[1]),
	.B(rst),
	.Y(n_7));
   NOR2BX1 g1013__6131 (.AN(a[5]),
	.B(rst),
	.Y(n_6));
   NOR2BX1 g1015__1881 (.AN(a[6]),
	.B(rst),
	.Y(n_5));
   NOR2BX1 g1016__5115 (.AN(a[1]),
	.B(rst),
	.Y(n_4));
   NOR2BX1 g1012__7482 (.AN(b[0]),
	.B(rst),
	.Y(n_3));
   NOR2BX1 g1014__4733 (.AN(b[6]),
	.B(rst),
	.Y(n_2));
   NOR2BX1 g1021__6161 (.AN(b[4]),
	.B(rst),
	.Y(n_1));
   NOR2BX1 g1023__9315 (.AN(b[5]),
	.B(rst),
	.Y(n_0));
endmodule

