
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 18 2026 12:56:19 IST (Feb 18 2026 07:26:19 UTC)

// Verification Directory fv/reg_adder 

module reg_adder(clk, rst, a, b, sum_q);
  input clk, rst;
  input [7:0] a, b;
  output [8:0] sum_q;
  wire clk, rst;
  wire [7:0] a, b;
  wire [8:0] sum_q;
  wire [7:0] a_reg;
  wire [7:0] b_reg;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  DFFQXL \sum_q_reg[8] (.CK (clk), .D (n_53), .Q (sum_q[8]));
  DFFQXL \sum_q_reg[7] (.CK (clk), .D (n_54), .Q (sum_q[7]));
  NOR2BX1 g950__2398(.AN (n_52), .B (rst), .Y (n_54));
  NOR2BX1 g951__5107(.AN (n_51), .B (rst), .Y (n_53));
  ADDFXL g952__6260(.A (a_reg[7]), .B (b_reg[7]), .CI (n_48), .CO
       (n_51), .S (n_52));
  DFFQXL \sum_q_reg[6] (.CK (clk), .D (n_50), .Q (sum_q[6]));
  NOR2BX1 g954__4319(.AN (n_49), .B (rst), .Y (n_50));
  ADDFX1 g955__8428(.A (b_reg[6]), .B (a_reg[6]), .CI (n_45), .CO
       (n_48), .S (n_49));
  DFFQXL \sum_q_reg[5] (.CK (clk), .D (n_47), .Q (sum_q[5]));
  NOR2BX1 g957__5526(.AN (n_46), .B (rst), .Y (n_47));
  ADDFX1 g958__6783(.A (b_reg[5]), .B (a_reg[5]), .CI (n_42), .CO
       (n_45), .S (n_46));
  DFFQXL \sum_q_reg[4] (.CK (clk), .D (n_44), .Q (sum_q[4]));
  NOR2BX1 g960__3680(.AN (n_43), .B (rst), .Y (n_44));
  ADDFX1 g961__1617(.A (b_reg[4]), .B (a_reg[4]), .CI (n_39), .CO
       (n_42), .S (n_43));
  DFFQXL \sum_q_reg[3] (.CK (clk), .D (n_41), .Q (sum_q[3]));
  NOR2XL g963__2802(.A (n_40), .B (rst), .Y (n_41));
  DFFQXL \sum_q_reg[2] (.CK (clk), .D (n_38), .Q (sum_q[2]));
  AOI21XL g965__1705(.A0 (n_36), .A1 (n_35), .B0 (n_37), .Y (n_40));
  OAI21X1 g966__5122(.A0 (n_17), .A1 (n_34), .B0 (n_16), .Y (n_39));
  DFFQXL \sum_q_reg[1] (.CK (clk), .D (n_33), .Q (sum_q[1]));
  NOR2XL g967__8246(.A (n_32), .B (rst), .Y (n_38));
  NOR2XL g968__7098(.A (n_36), .B (n_35), .Y (n_37));
  CLKINVX1 g969(.A (n_35), .Y (n_34));
  NOR2XL g973__6131(.A (n_31), .B (rst), .Y (n_33));
  AOI21XL g971__1881(.A0 (n_29), .A1 (n_28), .B0 (n_30), .Y (n_32));
  OAI21X1 g972__5115(.A0 (n_20), .A1 (n_27), .B0 (n_19), .Y (n_35));
  DFFQXL \sum_q_reg[0] (.CK (clk), .D (n_23), .Q (sum_q[0]));
  AOI21XL g977__7482(.A0 (n_25), .A1 (n_24), .B0 (n_26), .Y (n_31));
  NOR2XL g974__4733(.A (n_29), .B (n_28), .Y (n_30));
  CLKINVX1 g975(.A (n_28), .Y (n_27));
  NOR2XL g979__6161(.A (n_25), .B (n_24), .Y (n_26));
  NOR2XL g980__9315(.A (n_18), .B (rst), .Y (n_23));
  OAI21X1 g978__9945(.A0 (n_25), .A1 (n_21), .B0 (n_22), .Y (n_28));
  NOR2BXL g981__2883(.AN (n_22), .B (n_21), .Y (n_24));
  NAND2BXL g982__2346(.AN (n_20), .B (n_19), .Y (n_29));
  OAI21X1 g983__1666(.A0 (a_reg[0]), .A1 (b_reg[0]), .B0 (n_25), .Y
       (n_18));
  NAND2BXL g984__7410(.AN (n_17), .B (n_16), .Y (n_36));
  NAND2XL g985__6417(.A (a_reg[1]), .B (b_reg[1]), .Y (n_22));
  NOR2XL g987__5477(.A (a_reg[2]), .B (b_reg[2]), .Y (n_20));
  NOR2XL g988__2398(.A (a_reg[3]), .B (b_reg[3]), .Y (n_17));
  NOR2XL g986__5107(.A (a_reg[1]), .B (b_reg[1]), .Y (n_21));
  NAND2XL g990__6260(.A (a_reg[2]), .B (b_reg[2]), .Y (n_19));
  NAND2XL g989__4319(.A (a_reg[3]), .B (b_reg[3]), .Y (n_16));
  NAND2XL g991__8428(.A (a_reg[0]), .B (b_reg[0]), .Y (n_25));
  DFFQX1 \b_reg_reg[7] (.CK (clk), .D (n_14), .Q (b_reg[7]));
  DFFQX1 \a_reg_reg[6] (.CK (clk), .D (n_5), .Q (a_reg[6]));
  DFFQX1 \a_reg_reg[4] (.CK (clk), .D (n_8), .Q (a_reg[4]));
  DFFQX1 \a_reg_reg[5] (.CK (clk), .D (n_6), .Q (a_reg[5]));
  DFFQX1 \b_reg_reg[5] (.CK (clk), .D (n_0), .Q (b_reg[5]));
  DFFQX1 \a_reg_reg[1] (.CK (clk), .D (n_4), .Q (a_reg[1]));
  DFFQX1 \a_reg_reg[2] (.CK (clk), .D (n_12), .Q (a_reg[2]));
  DFFQX1 \b_reg_reg[0] (.CK (clk), .D (n_3), .Q (b_reg[0]));
  DFFQX1 \b_reg_reg[4] (.CK (clk), .D (n_1), .Q (b_reg[4]));
  DFFQX1 \a_reg_reg[7] (.CK (clk), .D (n_10), .Q (a_reg[7]));
  DFFQX1 \b_reg_reg[6] (.CK (clk), .D (n_2), .Q (b_reg[6]));
  DFFQX1 \a_reg_reg[3] (.CK (clk), .D (n_9), .Q (a_reg[3]));
  DFFQX1 \a_reg_reg[0] (.CK (clk), .D (n_11), .Q (a_reg[0]));
  DFFQX1 \b_reg_reg[3] (.CK (clk), .D (n_15), .Q (b_reg[3]));
  DFFQX1 \b_reg_reg[2] (.CK (clk), .D (n_13), .Q (b_reg[2]));
  DFFQX1 \b_reg_reg[1] (.CK (clk), .D (n_7), .Q (b_reg[1]));
  NOR2BX1 g1009__5526(.AN (b[3]), .B (rst), .Y (n_15));
  NOR2BX1 g1018__6783(.AN (b[7]), .B (rst), .Y (n_14));
  NOR2BX1 g1019__3680(.AN (b[2]), .B (rst), .Y (n_13));
  NOR2BX1 g1008__1617(.AN (a[2]), .B (rst), .Y (n_12));
  NOR2BX1 g1022__2802(.AN (a[0]), .B (rst), .Y (n_11));
  NOR2BX1 g1010__1705(.AN (a[7]), .B (rst), .Y (n_10));
  NOR2BX1 g1011__5122(.AN (a[3]), .B (rst), .Y (n_9));
  NOR2BX1 g1020__8246(.AN (a[4]), .B (rst), .Y (n_8));
  NOR2BX1 g1017__7098(.AN (b[1]), .B (rst), .Y (n_7));
  NOR2BX1 g1013__6131(.AN (a[5]), .B (rst), .Y (n_6));
  NOR2BX1 g1015__1881(.AN (a[6]), .B (rst), .Y (n_5));
  NOR2BX1 g1016__5115(.AN (a[1]), .B (rst), .Y (n_4));
  NOR2BX1 g1012__7482(.AN (b[0]), .B (rst), .Y (n_3));
  NOR2BX1 g1014__4733(.AN (b[6]), .B (rst), .Y (n_2));
  NOR2BX1 g1021__6161(.AN (b[4]), .B (rst), .Y (n_1));
  NOR2BX1 g1023__9315(.AN (b[5]), .B (rst), .Y (n_0));
endmodule

